# Generated by Django on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_adminsetting_admintoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absent_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
