# Generated by Django 4.2.7 on 2026-04-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_absent_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='already_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('absent', 'Absent'), ('on_time', 'On Time'), ('late', 'Late'), ('leave', 'On Leave')], default='absent', max_length=20),
        ),
    ]
