# Generated by Django 5.2.8 on 2026-03-06 11:23

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_batch_department_alter_student_face_encoding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='Student email for notifications', max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Teacher email for notifications', max_length=254, null=True)),
                ('face_encoding', models.BinaryField(blank=True, default=accounts.models.default_encoding, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.teacher_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
            ],
        ),
    ]
