# Generated by manual edit to add phone field to Teacher
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_email_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, help_text='Teacher phone number', max_length=32, null=True),
        ),
    ]
